In [1]:
from google.colab import files

uploaded = files.upload()

Saving perfom.zip to perfom (1).zip

In [3]:
import zipfile
import os

with zipfile.ZipFile("perfom (1).zip", "r") as zip_ref:
    zip_ref.extractall("student_data")

print(os.listdir("student_data"))

['StudentsPerformance.csv']

In [4]:
import pandas as pd

df = pd.read_csv("student_data/StudentsPerformance.csv")

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape: (1000, 8)

Columns:
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

Data Types:
gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

Missing Values:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [7]:
df.to_excel("StudentsPerformance.xlsx", index=False)

In [8]:
df.to_json("StudentsPerformance.json", orient="records", indent=4)

In [9]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (23.0.1)

In [10]:
df.to_parquet("StudentsPerformance.parquet", index=False)

In [11]:
import os

print(os.listdir())

['.config', 'perfom (1).zip', 'StudentsPerformance.parquet', 'StudentsPerformance.xlsx', 'StudentsPerformance.json', 'student_data', 'perfom.zip', 'sample_data']

In [12]:
df_excel = pd.read_excel("StudentsPerformance.xlsx")

print(df_excel.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [13]:
df_json = pd.read_json("StudentsPerformance.json")

print(df_json.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [14]:
df_parquet = pd.read_parquet("StudentsPerformance.parquet")

print(df_parquet.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [15]:
print("Original CSV:", df.shape)
print("Excel:", df_excel.shape)
print("JSON:", df_json.shape)
print("Parquet:", df_parquet.shape)

Original CSV: (1000, 8)
Excel: (1000, 8)
JSON: (1000, 8)
Parquet: (1000, 8)

In [16]:
import os

files = {
    "CSV": "student_data/StudentsPerformance.csv",
    "Excel": "StudentsPerformance.xlsx",
    "JSON": "StudentsPerformance.json",
    "Parquet": "StudentsPerformance.parquet"
}

for name, file in files.items():
    size = os.path.getsize(file) / 1024
    print(name, ":", round(size, 2), "KB")

CSV : 70.35 KB
Excel : 37.45 KB
JSON : 279.55 KB
Parquet : 10.07 KB

In [17]:
math_avg = df["math score"].mean()

print("Average Math Score:", math_avg)

Average Math Score: 66.089

In [18]:
reading_avg = df["reading score"].mean()

print("Average Reading Score:", reading_avg)

Average Reading Score: 69.169

In [19]:
writing_avg = df["writing score"].mean()

print("Average Writing Score:", writing_avg)

Average Writing Score: 68.054

In [20]:
print("Average Math Score:", df["math score"].mean())
print("Average Reading Score:", df["reading score"].mean())
print("Average Writing Score:", df["writing score"].mean())

Average Math Score: 66.089
Average Reading Score: 69.169
Average Writing Score: 68.054

In [22]:
math_above_80 = df[df["math score"] > 80]

In [23]:
math_above_80

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
981,male,group D,some high school,standard,none,81,78,78
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

In [24]:
print("Number of students:", len(math_above_80))

Number of students: 176

In [26]:
math_above_80.to_csv(
    "StudentsPerformance_math_above_80.csv",
    index=False
)

In [27]:
import os

print(os.listdir())

['.config', 'perfom (1).zip', 'StudentsPerformance.parquet', 'StudentsPerformance_math_above_80.csv', 'StudentsPerformance.xlsx', 'StudentsPerformance.json', 'student_data', 'perfom.zip', 'sample_data']

In [28]:
print("Original DataFrame:", df.shape)
print("Excel DataFrame:", df_excel.shape)
print("JSON DataFrame:", df_json.shape)
print("Parquet DataFrame:", df_parquet.shape)
print("Students with Math Score > 80:", len(math_above_80))

Original DataFrame: (1000, 8)
Excel DataFrame: (1000, 8)
JSON DataFrame: (1000, 8)
Parquet DataFrame: (1000, 8)
Students with Math Score > 80: 176